In [2]:
import pandas as pd    # PANDAS is library for performing data analysis in python

In [3]:
hp_df=pd.read_csv('house_price.csv')   # here table is known as DATA FRAME

In [4]:
hp_df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [5]:
hp_df['SalePrice']   # to take a specific series(column)

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [6]:
hp_df['SalePrice'].dtype   # to find the data type of a particular column

dtype('int64')

In [7]:
hp_df.dtypes              # to find the data type of all series(column)

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...   
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [8]:
hp_df.shape   # no of rows and columns

(1460, 81)

In [9]:
hp_df['LotShape'].dtype   # columns with 'O'(object) data type are categorical columns

dtype('O')

In [10]:
hp_df.columns   # to see all the columns in data frame

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [11]:
hp_df[['MSZoning','SalePrice']]    # accessing two series in a data frame

MSZoning  SalePrice
0          RL     208500
1          RL     181500
2          RL     223500
3          RL     140000
4          RL     250000
...       ...        ...
1455       RL     175000
1456       RL     210000
1457       RL     266500
1458       RL     142125
1459       RL     147500

[1460 rows x 2 columns]

In [12]:
hp_df.describe()   # shows the mean,std percentiles of all columns

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [13]:
hp_df['SalePrice'].describe()   # mean for one column

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

In [14]:
hp_df.isnull().sum()   # .isnull().sum() returns the no of null values in each series

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [15]:
# to apply log for column

import numpy as np

hp_df['SalePrice'].apply(np.log)

0       12.247694
1       12.109011
2       12.317167
3       11.849398
4       12.429216
          ...    
1455    12.072541
1456    12.254863
1457    12.493130
1458    11.864462
1459    11.901583
Name: SalePrice, Length: 1460, dtype: float64

In [16]:
# Que-->print year interms of which century it belongs to 

def get_century(year):
    if year<2000:
        return '20th century'
    if year>=2000:
        return '21st century'

hp_df['YearBuilt'].apply(get_century)


0       21st century
1       20th century
2       21st century
3       20th century
4       21st century
            ...     
1455    20th century
1456    20th century
1457    20th century
1458    20th century
1459    20th century
Name: YearBuilt, Length: 1460, dtype: object

# FILL MISSING VALUES

In [17]:
hp_df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [18]:
hp_df['LotFrontage']

0       65.0
1       80.0
2       68.0
3       60.0
4       84.0
        ... 
1455    62.0
1456    85.0
1457    66.0
1458    68.0
1459    75.0
Name: LotFrontage, Length: 1460, dtype: float64

In [19]:
hp_df['LotFrontage'].mean()  # mean of a column

70.04995836802665

In [20]:
hp_df['LotFrontage'].fillna(hp_df['LotFrontage'].mean()) # now missing values are replaced by mean

0       65.0
1       80.0
2       68.0
3       60.0
4       84.0
        ... 
1455    62.0
1456    85.0
1457    66.0
1458    68.0
1459    75.0
Name: LotFrontage, Length: 1460, dtype: float64

In [21]:
hp_df['LotFrontage'].isnull().sum()  #but we are getting missing values again so use inplace=True

259

In [22]:
hp_df['LotFrontage'].fillna(hp_df['LotFrontage'].mean(),inplace=True)

hp_df['LotFrontage'].isnull().sum()

0

# custom dataframe

In [23]:
std_info=pd.DataFrame({'student':['mans','gori','bhula'],
                      'scores':[99,95,92],
                      'location':['gun','hyd','rjy']})
std_info

student  scores location
0    mans      99      gun
1    gori      95      hyd
2   bhula      92      rjy

In [24]:
std_info.columns

Index(['student', 'scores', 'location'], dtype='object')

In [25]:
std_info.shape

(3, 3)

In [26]:
cus_df=pd.DataFrame({'column_name':hp_df.columns,
                    'missing_value_count':hp_df.isnull().sum(),
                    'missing_value_percentage':hp_df.isnull().sum()/hp_df.shape[0]*100})

cus_df

column_name  missing_value_count  missing_value_percentage
Id                        Id                    0                       0.0
MSSubClass        MSSubClass                    0                       0.0
MSZoning            MSZoning                    0                       0.0
LotFrontage      LotFrontage                    0                       0.0
LotArea              LotArea                    0                       0.0
...                      ...                  ...                       ...
MoSold                MoSold                    0                       0.0
YrSold                YrSold                    0                       0.0
SaleType            SaleType                    0                       0.0
SaleCondition  SaleCondition                    0                       0.0
SalePrice          SalePrice                    0                       0.0

[81 rows x 3 columns]

# categorical and continuous columns

In [27]:
# QUE --> put all the continuos and categorical in two different lists

con_cols=[]
cat_cols=[]

for col in hp_df.columns:
    if hp_df[col].dtype=='int64' or hp_df[col].dtype=='float64':
        con_cols.append(col)
    
    if hp_df[col].dtype=='object':
        cat_cols.append(col)
        
print(con_cols)

print(cat_cols)
    


['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']
['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'Gara

In [29]:
hp_df['SalePrice']

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [33]:
np.corrcoef(hp_df['SalePrice'],hp_df['LotArea'])

array([[1.        , 0.26384335],
       [0.26384335, 1.        ]])

In [31]:
for col in con_cols:
    if np.corrcoef(hp_df[col],hp_df['SalePrice'])
        


[[ 1.         -0.02191672]
 [-0.02191672  1.        ]]
[[ 1.         -0.08428414]
 [-0.08428414  1.        ]]
[[1.         0.33490085]
 [0.33490085 1.        ]]
[[1.         0.26384335]
 [0.26384335 1.        ]]
[[1.        0.7909816]
 [0.7909816 1.       ]]
[[ 1.         -0.07785589]
 [-0.07785589  1.        ]]
[[1.         0.52289733]
 [0.52289733 1.        ]]
[[1.         0.50710097]
 [0.50710097 1.        ]]
[[ 1. nan]
 [nan nan]]
[[1.         0.38641981]
 [0.38641981 1.        ]]
[[ 1.         -0.01137812]
 [-0.01137812  1.        ]]
[[1.         0.21447911]
 [0.21447911 1.        ]]
[[1.         0.61358055]
 [0.61358055 1.        ]]
[[1.         0.60585218]
 [0.60585218 1.        ]]
[[1.        0.3193338]
 [0.3193338 1.       ]]
[[ 1.         -0.02560613]
 [-0.02560613  1.        ]]
[[1.         0.70862448]
 [0.70862448 1.        ]]
[[1.         0.22712223]
 [0.22712223 1.        ]]
[[ 1.         -0.01684415]
 [-0.01684415  1.        ]]
[[1.         0.56066376]
 [0.56066376 1.   

In [ ]:
# write the above code using list comprehension

cat_cols=[col for col in hp_df.columns if hp_df[col].dtype=='int64' or hp_df[col].dtype=='float64']

con_cols=[col for col in hp_df.columns if hp_df[col].dtype=='object'] 

print(con_cols)

print(cat_cols)

# BOX PLOT

In [ ]:
# It is the uni-variate analysis
# only continuous varaiable series(column) we can do boxplot
# to find boxplot u must import boxplot lib

In [ ]:
import matplotlib.pyplot as plt        # matplotlib,seaborn --> data visualization

In [ ]:
plt.boxplot(hp_df['SalePrice'])

In [ ]:
plt.boxplot(hp_df['MSSubClass'])

In [ ]:
# using seaborn

import seaborn as sns   # in seaborn 

In [ ]:
sns.boxplot(hp_df['SalePrice'])

In [ ]:
sns.boxplot(hp_df['MSSubClass'])

# scatter plot

In [ ]:
# it is the bi-variate analysis --> need two columns

plt.scatter(hp_df['LotArea'],hp_df['SalePrice'])

# Histogram using matplot

In [ ]:
plt.hist(hp_df['SalePrice'])

In [ ]:
plt.hist(hp_df['LotArea'])

# Histogram using seaborn

In [ ]:
sns.distplot(hp_df['SalePrice'])

# ANOVA TEST --> for one categorical and one continuous

In [ ]:
# Anova test is b/w one continuous and one categorical series

In [ ]:
from scipy.stats import f_oneway

In [ ]:
hp_df['SalePrice']    # continuous variables

hp_df['MSZoning']     # categorical variables

In [ ]:
hp_df['MSZoning'].value_counts()   # .value_counts() shows no. of diff categories in a series
                                   # in MSZoning there are 5 categories i.e; RL,RM,FV,RH,C(all)

# FILTERING

In [ ]:
hp_df[hp_df['MSZoning']=='RL']['SalePrice']  # this is filtering
                                            # so here we took only 'RL' category in MSZoning column
                                            # there are 1151 RL's in MSZoning

In [ ]:
hp_df[hp_df['MSZoning']=='RM']['SalePrice']  # for 'RM', there are 218 RM's in MSZoning

In [ ]:
# filter all the five categories of MSZoning

RM_list=list(hp_df[hp_df['MSZoning']=='RM']['SalePrice'])
RL_list=list(hp_df[hp_df['MSZoning']=='RL']['SalePrice'])
FV_list=list(hp_df[hp_df['MSZoning']=='FV']['SalePrice'])
RH_list=list(hp_df[hp_df['MSZoning']=='RH']['SalePrice'])
c_all=list(hp_df[hp_df['MSZoning']=='C (all)']['SalePrice'])   # there should be no mistake of category name 

In [ ]:
# use f_oneway and put all the above 5 lists according to documentation

f_oneway(RM_list,RL_list,FV_list,RH_list,c_all)

In [ ]:
p_value=f_oneway(RM_list,RL_list,FV_list,RH_list,c_all)[1]   # indexing to get only p-value
 
p_value

In [ ]:
# so above p-value=0.0000000000......008176 which is less then S.L(significance level)
# so if p-value<S.L, then reject Ho --> reject there is co-relation
# conclusion is there is co-relation.

In [ ]:
# full program in single cell

hp_df['MSZoning'].value_counts()

RM_list=list(hp_df[hp_df['MSZoning']=='RM']['SalePrice'])
RL_list=list(hp_df[hp_df['MSZoning']=='RL']['SalePrice'])
FV_list=list(hp_df[hp_df['MSZoning']=='FV']['SalePrice'])
RH_list=list(hp_df[hp_df['MSZoning']=='RH']['SalePrice'])
c_all=list(hp_df[hp_df['MSZoning']=='C (all)']['SalePrice'])

f_oneway(RM_list,RL_list,FV_list,RH_list,c_all)

p_value=f_oneway(RM_list,RL_list,FV_list,RH_list,c_all)[1]   # indexing to get only p-value
 
p_value

In [ ]:
# the above code using for loop

mszone=hp_df['MSZoning'].value_counts().index

p_value=f_oneway(*([hp_df[hp_df['MSZoning']==ele]['SalePrice'] for ele in mszone]))[1]
    
print(p_value)


In [ ]:
# the above ANOVA test is only for one categorical column and continuos('SalePrice')

# QUE--> check co-relation for all categorical columns and SalePrice

In [ ]:
cat_cols=[col for col in hp_df.columns if hp_df[col].dtype=='object']

def anova(col):
    categor_list=list(hp_df[col].value_counts().index)
    
    result=f_oneway(*([hp_df[hp_df[col]==cat]['SalePrice'] for cat in categor_list]))
    
    return result[1],col

[anova(col)for col in cat_cols]


In [ ]:
len([anova(col) for col in cat_cols])

In [ ]:
# QUE--> for above anova test check the co-relation b/w the columns and SalePrice

sig_val=0.05

corre_cols=[]
noncorre_cols=[]

p_values=[anova(col) for col in cat_cols]

for ele in p_values:
    if ele[0]<sig_val:
        corre_cols.append(ele[1])
        
    if ele[0]>sig_val:
        noncorre_cols.append(ele[1])    
        
print(corre_cols)
 
print(noncorre_cols)

In [ ]:
len(corre_cols)

In [ ]:
len(noncorre_cols)

# STANDARD SCALER

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# follow documentation

std_scaler=StandardScaler()   # create a object

std_scaled=std_scaler.fit_transform(np.array(hp_df['LotArea']).reshape(-1,1))  # fit_transform method in StandardScaler

std_scaled

In [ ]:
std_scaled.mean()     # mean is approx = 0 as studied

In [ ]:
std_scaled.std()    # varaiance or std is = 1

# MIN-MAX SCALER

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
# follow documentation

minmax_scalar=MinMaxScaler()  # create a object

mm_scaled=minmax_scalar.fit_transform(np.array(hp_df['LotArea']).reshape(-1,1))  # got values b/w (0,1)
mm_scaled

# TRAIN_SPLIT - SKLEARN

In [ ]:
# for train split as discussed in notes, we have to divide into four parts
# seperate the output from the dataset using drop

y=hp_df['SalePrice']  # assign saleprice to a variable, so output=y
y

In [ ]:
# now drop saleprice from dataset

hp_df=hp_df.drop(columns=['SalePrice'])

hp_df.columns # there is no sale price in hp_df now

In [ ]:
# now start train test split
# import sklearn --> machine learning documentation

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(hp_df,y,test_size=0.2,random_state=42) 

# do not change the order of X_train,X_test,y_train,y_test
# test_size represents how much you are splitting the data, you gave test_split=0.2, so test data=20% and train data=80%
# random_state is given because if we did not give that random_state, the train data takes random values for each iteration
# random_state should be assigned some value so that the data you took randomly is fixed for that value cycle.

In [ ]:
X_train  # input train data

In [ ]:
X_test    # input test data

In [ ]:
y_train    # output train data

In [ ]:
y_test    # output test data